alias gst 'git status'
alias glg 'git log'
alias gp 'git push'
alias gcmsg 'git commit -m'
alias gcam 'git add -A && git commit -m'
alias gba 'git branch -vv'
alias gco 'git checkout'
alias gcb 'git checkout -b'
alias gbr 'git branch -r'
alias gl 'git pull'
alias grl 'git rev-list ...main --count'
alias grb 'git rebase -i'
alias gd 'git diff'
