# Set terminal mode to 256color
set -g default-terminal "xterm-ghostty"

# Set default shell
run-shell 'tmux set-option -g default-shell "$(which fish)"'

# Unbind default and set new prefix
set -g prefix C-a
unbind C-b

# Ensure that we can send Ctrl-a to other apps
bind C-a send-prefix

# Set delay between prefix and command
set -s escape-time 0

# Set base index to 1
set -w -g pane-base-index 1
set -g base-index 6
set -g renumber-windows on
set -g set-clipboard on

# reload source file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuration reloaded"

# Split panes
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind y kill-pane

# Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Cycle between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Rezie panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r m resize-pane -Z

# Enable mouse
set -g mouse on

# Styling
set -w -g pane-border-lines heavy
set -g pane-border-indicators arrows

# New styling
status_bg="#1E2326"    # Black text
inactive_window_fg="#2E383C"
active_window_fg="#A7C080"
active_window_text="#1E2326"
default_text="#D3C6AA"
current_dir_text="#7FBBB3"

# --- General Status Bar Style ---
# set -g status-style bg=${status_fg}
# set -g status-left-length 40
# set -g status-right-length 150
# set -g message-style fg=white,bg=color242,bold

# --- Status Left (Session) ---
set -g status-left "" # Remove the window name on the left side

# --- Window Status Format ---
# Inactive Window: Separator  | Window Name | Separator 
set -g window-status-format "#[fg=${inactive_window_fg},bg=${status_bg}]#[fg=${default_text},bg=${inactive_window_fg}] #W #[fg=${inactive_window_fg},bg=${status_bg}]"

# Active Window: Separator  | Window Name (Zoom Indicator) | Separator 
set -g window-status-current-format "#[fg=${active_window_fg},bg=${status_bg}]#[fg=${active_window_text},bg=${active_window_fg},bold] #W#{?window_zoomed_flag,(),} #[fg=${active_window_fg},bg=${status_bg}]"

# --- Status Right (Directory & Time) ---
# Directory | Separator  | Time/Date
set -g status-right "\
#[fg=${current_dir_text},bold,bg=${status_bg}] #{b:pane_current_path} \
#[fg=${default_text},bold,bg=${status_bg}] #S \
#[fg=${default_text},bg=${status_bg}] %H:%M %m-%d-%Y \
"

# Text configuration
set -w -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind p
bind p paste-buffer

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse
unbind PageUP
unbind Escape
bind PageUP copy-mode
bind Escape copy-mode
